portfolios:
  - chain: solana
    protocol: whirlpools
    positions:
      # stSOL/BTC
      - pool: J7qn7AvZ4QK9qT6BikVBKA3hUp89Lg9UkqJmXZQEjRxq
        strategy: one-tick
        ticks: 50
        swap: false

      # mSOL/wBTC
      - pool: H1fREbTWrkhCs2stH3tKANWJepmqeF9hww4nWRYrM7uV
        strategy: one-tick
        ticks: 50
        swap: false

      # mSOL/whETH
      - pool: 6jZQFLhSAzTYfo33MSQYvwKvZYwxat8kUa29Mz63oHN9
        strategy: one-tick
        ticks: 50
        swap: false
